<div class="container" id="basket">

	<table>
		
		<thead>
			<tr>
				<th class="mobile"></th>
				<th>Nom</th>
				<th>Prix</th>
				<th>Quantité</th>
				<th>Prix total</th>
			</tr>
		</thead>

		<tbody>
			<?php 
			$ttc = 0;
			foreach ($basket as $product): ?>
			
			<tr>
				<td class="mobile">
					<img src="<?= $wwwUrl ?>/images/shop/<?= $product['ProductImage'] ?>" alt="<?= $product['ProductImage'] ?>" />
				</td>
				
				<td><?= $product['ProductName'] ?></td>
				
				<td><?= $product['ProductPrice'] ?>€</td>

				<form action="<?= $requestUrl ?>/basket" method="POST">
					<input type="hidden" name ="product" value="<?= $product['ProductID'] ?>">

					<td class="nowrap"><!--Bouton de modification de la quantité-->
						<select name="quantity">
							<?php 
							if($product["quantity"] <= 10){
								$i = ($product["quantityMax"] > 10) ? 10 : $product["quantityMax"];
							}
							else{
								$i = $product["quantity"];
							}
							
							for($i; $i>0; $i--): ?>
									
								<?php if($i == $product["quantity"]): ?>
									<option selected value="<?= $product["quantity"] ?>"><?=$product["quantity"]?></option>
									
								<?php else: ?>
									<option value ="<?= $i ?>"><?= $i?></option>
									
								<?php endif; ?>
							<?php endfor; ?>
						</select>
						
						<button type="submit" name="button" value="editQty" class="icone"><i class="fas fa-check"></i></button>
					</td>
					
					<td class="nowrap">
						<?= $product["ProductPrice"]*$product["quantity"] ?> €
						<?php $ttc += ($product["ProductPrice"]*$product["quantity"]) ?>

						<!--Bouton de suppression du produit-->
						<button type="submit" name="button" value="deleteProduct" class="icone"><i class="fas fa-times"></i></button>
					</td>
				</form>

			</tr>
			<?php endforeach; ?>
			
			<tr>
				<td class="mobile"></td>
				<td></td>
				<td>(TVA 20%)</td>
				<td>Prix HT</td>
				<td><?= round(str_replace(",", ".", $ttc*0.8), 2) ?> €</td>
			</tr>
			
			<tr>
				<td class="mobile"></td>
				<td></td>
				<td></td>
				<td>Prix TTC</td>
				<td><?= $ttc ?> €</td>
			</tr>
		</tbody>
		
	</table>

	<div class="centerButton">
		<a href="<?= $requestUrl ?>/basket/order" class="button">Valider le panier</a>
		<a href="<?= $requestUrl ?>/basket/empty" class="button">Vider le panier</a>
	</div>

</div>