<div class="container" id="details">
	
	<h2>Détails de la commande #<?= $orderID ?></h2>

	<table>
		<thead>
			<th>Article</th>
			<th>Prix unitaire</th>
			<th>Quantité</th>
			<th>Prix HT</th>
			<th>Prix TTC</th>
		</thead>

		<tbody>
			<?php 	
				$totalHT = 0;
				$totalTTC = 0;
				foreach($details as $detail): 
			?>
			<?php 	
				$totalHT = $detail["OrderHT"];
				$totalTTC = $detail["OrderTTC"]; 
			?>
			<tr>
				<td><?= $detail["ProductName"] ?></td>
				<td><?= $detail["ProductPrice"] ?> €</td>
				<td><?= $detail["DetailsQty"] ?></td>
				<td><?= $detail["ProductPrice"]*$detail["DetailsQty"]*0.8 ?> €</td>
				<td><?= $detail["ProductPrice"]*$detail["DetailsQty"] ?> €</td>
			</tr>
			<?php endforeach; ?>

			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td>Prix HT (TVA 20%)</td>
				<td><?= $totalHT ?> €</td>
			</tr>
			
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td>Prix TTC</td>
				<td><?= $totalTTC ?> €</td>
			</tr>
		</tbody>
	</table>

	<div>
		<?php if($session->isAdmin() == true): ?>
		<a href="<?= $requestUrl ?>/admin" title="Retour" class="button">Retour</a>
		
		<?php else: ?>
		<a href="<?= $requestUrl ?>/account" title="Retour" class="button">Retour</a>
		
		<?php endif; ?>
	</div>
</div>