<div class="container" id="flash">

	<article>
		<h2>Le board custom c'est quoi ?</h2>

		<p>Je réalise des <span>flash</span></p>
		<p>Un flash c'est quoi ?</p>
		<p>Une petite illustration, un peu comme un tatoo !</p>
		<p>Du coup, ça permet de <span>Décorer</span> ou <span>Personnaliser</span></p>
		<p>Je fais aussi des <span>cover</span></p>
		<p>Et le cover, c'est pour recouvrir une réparation.</p>
		<p>Et je réalise tout ça sur des <span>planches de surf</span></p>
	</article>

	<div class="container-grid-flash">
		<img src="<?= $wwwUrl ?>/images/exemples/baleine.png" alt="">
		<img src="<?= $wwwUrl ?>/images/exemples/board_custom.png" alt="">
		<img src="<?= $wwwUrl ?>/images/exemples/palmier.png" alt="">
		<img src="<?= $wwwUrl ?>/images/exemples/coeur.png" alt="">
		<img src="<?= $wwwUrl ?>/images/exemples/custom_richard.png" alt="">
		<img src="<?= $wwwUrl ?>/images/exemples/cobra.png" alt="">
		<img src="<?= $wwwUrl ?>/images/exemples/palmier2.png" alt="">
		<img src="<?= $wwwUrl ?>/images/exemples/flower_board.png" alt="">
		<img src="<?= $wwwUrl ?>/images/exemples/planche_croco.png" alt="">
	</div>
</div>