<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="<?php	if(!empty($content)){
												echo $content;
											}
											else {
												echo "Romy Art par Romane Jacquemin - Illustrations et décorations en flash ou customisation, tote bags, planches de surf, ardoises, décoration murale et vitrines";
											}
										?>" />
	<meta http-equiv= "X-UA-Compatible" content= "ie-edge">
	
	<title>
		<?php if(!empty($title)) { 
					echo $title; 
				}
				else{
					echo "Romy Art - Eshop de tote bags et décorations";
				}
		?>
	</title>

	<!-- Favicon -->
	<link rel="icon" type="image/png" href="<?= $wwwUrl ?>/images/layout/header1.png">

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css2?family=Amatic+SC&family=Source+Sans+Pro&display=swap" rel="stylesheet">

	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.0/css/all.css" />

	<!-- Librairie jQuery -->
	<script src="https://code.jquery.com/jquery-2.1.0.min.js"></script>

	<!-- Code Javascript -->
	<script src="<?= $wwwUrl ?>/js/utilities.js"></script>

	<!-- Feuilles de styles -->
	<link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize.css" type="text/css">
	<link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css" type="text/css">

</head>

<body>

	<!-- En-tête commune -->
	<header>
		<div class="container">
			<a href="<?= $requestUrl ?>" title="Accueil" id="logo">
				<img id="logo-big" src="<?= $wwwUrl ?>/images/layout/header3.png" alt="Romy Artwork">
				<img id="logo-mobile" src="<?= $wwwUrl ?>/images/layout/header2.png" alt="Romy Artwork">
			</a>
	
			<div class="burger">
				<span id="burgerUser"><i class="fas fa-user"></i></span>
				<span id="burgerShop"><i class="fas fa-bars"></i></span>
			</div>
			
			<div id="headerNav">
				<nav id="userNav" class="flex menu">
					
					<?php if($session->isLogged() == true): ?>

						<div id="isLogged" class="flex">

							<!-- Partie Administration -->
							<?php if($session->isAdmin() == true): ?>
								<a href="<?= $requestUrl ?>/admin" title="Administration"><i class="fas fa-cogs"></i> Administration</a>
							<?php endif; ?>

							<!--Connecté-->
							<div class="flex">
								<a href="<?= $requestUrl ?>/account" title="Compte"><i class="fas fa-user mobile"></i> Mon compte</a>
								<p> / </p>
								<a href="<?= $requestUrl ?>/basket" title="Panier"><i class="fas fa-shopping-basket mobile"></i> Panier</a>
								<p> / </p>
								<a href="<?= $requestUrl ?>/user/logout" title="Déconnexion"><i class="fas fa-user-times mobile"></i> Déconnexion</a>
							</div>

						</div>

					<?php else: ?>
						<!--Pas connecté-->
						<a href="<?= $requestUrl ?>/user" title="Créer un compte"><i class="fas fa-user-plus"></i> Créer un compte</a>
						<p>/</p>
						<a href="<?= $requestUrl ?>/user/login" title="Se connecter"><i class="fas fa-user-check"></i> Se connecter</a>
					<?php endif; ?>
				</nav>

				<nav id="shopNav" class="flex menu">
					<a href="<?= $requestUrl ?>" title="Accueil"><i class="fas fa-home"></i> Accueil</a>

					<span class="roll">
						<a href="<?= $requestUrl ?>/portfolio" title="Portfolio"><i class="fas fa-book-open"></i> Portfolio <i class="fas fa-caret-down"></i></a>
						<span class="sousRoll">
							<a href="<?= $requestUrl ?>/portfolio/flash" title="Flash">Flash Personnalisables</a>
							<a href="<?= $requestUrl ?>/portfolio/deco" title="Décorations">Décoration intérieure</a>
							<a href="<?= $requestUrl ?>/portfolio/cartes" title="Cartes et Ardoises">Cartes et Ardoises</a>
							<a href="<?= $requestUrl ?>/portfolio/mur" title="Décor mural et vitrines">Décor mural et Vitrines</a>
						</span>
					</span>

					<a href="<?= $requestUrl ?>/shop" title="Boutique"><i class="fas fa-store-alt"></i> Boutique</a></li>
					<a href="<?= $requestUrl ?>/aboutme" title="About me"><i class="fas fa-user-tie"></i> About me</a>
					<a href="<?= $requestUrl ?>/contact" title="Contact"><i class="far fa-paper-plane"></i> Contact</a>
				</nav>
			</div>
		</div>

	</header>

	<main>
		<div class="defile">
			<h1 class="nowrap">Bienvenue sur RomyArt Shop !</h1>
		</div>

		<!-- Affichage du template lié à la vue -->
		<?php include $this->viewData['template'] ?>
	</main>

	<!-- Pied de page commun -->
	<footer>
		<div class="container">

			<p class="backToTop">
				<a href="#" title="Haut de page"><i class="fas fa-arrow-up"></i> Top</a>
			</p>

			<div id="contactNav" class="flex">
				<a href="https://www.facebook.com/romane.jacquemin.9" title="Page Facebook" target="_blank"><i class="fab fa-facebook"></i></a>
				<a href="https://www.instagram.com/romyartwork/" title="Page Instagram" target="_blank"><i class="fab fa-instagram"></i></a>
				<a href="mailto:romanejacquemmin@yahoo.fr" title="Email" target="_blank"><i class="far fa-envelope"></i></a>
			</div>

			<div id="footerNav" class="flex">
				<div>
					<h3><a href="<?= $requestUrl ?>" title="Accueil">Accueil</a></h3>
				</div>

				<div>
					<h3><a href="<?= $requestUrl ?>/shop" title="Boutique">Boutique</a></h3>
				</div>

				<div>
					<h3><a href="<?= $requestUrl ?>/portfolio" title="Portfolio">Portfolio</a></h3>
					<div class="flex">
						<a href="<?= $requestUrl ?>/portfolio/flash" title="Flash">Flash personnalisables</a>
						<a href="<?= $requestUrl ?>/portfolio/deco" title="Décorations">Décoration intérieure</a>
						<a href="<?= $requestUrl ?>/portfolio/cartes" title="Cartes et ardoises">Cartes et Ardoises</a>
						<a href="<?= $requestUrl ?>/portfolio/mur" title="Décor mural et vitrines">Décor mural et Vitrines</a>
					</div>
				</div>

				<div>
					<h3><a href="<?= $requestUrl ?>/aboutme" title="About me">A propos</a></h3>
				</div>
				<div>
					<h3><a href="<?= $requestUrl ?>/contact" title="Contact">Contact</a></h3>
				</div>
			</div>

			<div id="paymentNav" class="flex">
				<img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="visa">
				<img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="mastercard">
				<img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="paypal">
			</div>

			<div>
				<p><i class="far fa-copyright"></i> 2020 - Réalisé par <a href="mailto:ear.sophie@gmail.com" title="mail">Sophie EAR</a></p>
			</div>
		</div>
	</footer>

	<!-- Code principal JavaScript -->
	<script src="<?= $wwwUrl ?>/js/main.js"></script>
	<script src="<?= $wwwUrl ?>/js/slider.js"></script>

</body>
</html>