<section class="container" id="aboutMe">
	<h2>Romy Jacquemin</h2>

	<div class="flex">
		<article id="passion">
			<h2>Une passion riche</h2>

			<p><i class="fas fa-quote-left"></i> J'ai récemment ouvert ma micro entreprise en design et illustration, et propose une palette riche et variée. La personnalisation me permet de m'adapter aux envies de chacun.</p>
			<p>J'ai repris une formation en design textile il y a peu qui me permet de maîtriser certains outils informatiques tels que les logiciels de retouche Photoshop et Illustrator, utiles pour la conception de logo par exemple.</p>
			<p>Mon travail saisonnier dans les Landes me fait me pencher sur de nouvelles activités depuis peu, telles que la customisation de planches et d'espaces (vitrines et intérieurs). <i class="fas fa-quote-right"></i></p>
		</article>

		<article id="contactMoi">
			<h2>Contactez-moi !</h2>

			<p><i class="fas fa-quote-left"></i> Je réalise des illustrations sur mesure et sur différents supports.</p>
			<p><a href="<?= $requestUrl ?>/contact" title="Page contact">Contactez-moi</a> pour concrétiser vos envies ! <i class="fas fa-quote-right"></i></p>
		</article>

		<article id="tatooBoard">
			<h2>Tatoueuse de boards</h2>

			<p><i class="fas fa-quote-left"></i> Ma présence au sein du surf camp "The Spot" depuis deux saisons, m'a fait m'intéresser à ce milieu, et débuter les customisations de planches.</p>
			<p>Les "flash" sont personnalisables et permettent à chacun d'exprimer sa personnalité tandis que les custom de boards sont destinées à de la décoration intérieure. <i class="fas fa-quote-right"></i></p>
		</article>
	</div>
	
</section>