<div class="container container-grid-portfolio" id="portfolio" >

	<a href="<?= $requestUrl ?>/portfolio/flash" title="Ex Flash">
		<img src="<?= $wwwUrl ?>/images/icones/flash.png" alt="Icone Flash"/>
	</a>

	<a href="<?= $requestUrl ?>/portfolio/deco" title="Ex Deco">
		<img src="<?= $wwwUrl ?>/images/icones/decorations.png" alt="Icone Décoration Intérieure"/>
	</a>

	<a href="<?= $requestUrl ?>/portfolio/cartes" title="Ex Cartes">
		<img src="<?= $wwwUrl ?>/images/icones/cartes-et-ardoises.png" alt="Icone Cartes et Ardoises"/>
	</a>

	<a href="<?= $requestUrl ?>/portfolio/mur" title="Ex Mur">
		<img src="<?= $wwwUrl ?>/images/icones/decors-et-vitrines.png" alt="Icone Mur et Vitrine"/>
	</a>
	
</div>