<div class="container exemple" id="deco">

	<h2>Décorez votre intérieur</h2>
	
	<div class="flex">

		
		<img src="<?= $wwwUrl ?>/images/exemples/planche_detail.jpg" alt="Planche de surf rouge détail">

		<img src="<?= $wwwUrl ?>/images/exemples/planche_view.jpg" alt="Planche de surf rouge penchée">

	</div>

	<img src="<?= $wwwUrl ?>/images/exemples/planche_entiere.png" alt="Planche de surf rouge">
	
</div>