<section class="container" id="contact">

	<h2>Contact</h2>
	
	<article>
		<p>Un achat à réaliser sur la boutique, ou une demande d'illustration personnalisée ?</p>

		<p>Pour me contacter, rien de plus simple ! Tu peux m'envoyer un mail à cette adresse :</p>

		<a href="mailto:romanejacquemin@yahoo.fr" title="Adresse email">romanejacquemin@yahoo.fr</a>

		<p>ou directement sur ma page <a href="https://www.instagram.com/romyartwork/" title="Page Instagram">Instagram</a> en MP</p>

	</article>
	
</section>